Pal 421 helm jobs for kafka
gchq/Palisade-services pull request #118
Opened 2020-04-22 14:57 UTC by nw1984

Create a triggered helm job (post-install) that creates the kafka queues that will be used for the streaming architecture.
The job created is set for a delete policy of before-hook-creation so that the hook remains in existence and can be debugged after installation.

2020-04-28 16:16 UTC, dev-958 requested changes
Similar comment to other chart regarding namespaces but also your script always sets partition and replica counts to 1 by the look of it. I think these need to be added into the mix as parameters too, unless you have another idea.

2020-04-28 16:16 UTC, dev-958 commented on charts/kafka-queues/values.yaml
> +  - palisade-to-user
It's convention to name a queue after it's producer stream (as there is usually only one producer but can be many consumers). So; palisade, user, resource ...

2020-04-28 16:16 UTC, dev-958 commented on charts/kafka/charts/zookeeper/templates/service.yaml
> +  annotations:
annotations: is in the wrong place, it should be at the same level as name: above.

2020-05-06 08:13 UTC, dev-958 submitted a review, later dismissed

2020-05-06 11:35 UTC, ac74475 requested changes

2020-05-06 11:35 UTC, ac74475 commented on charts/kafka-queues/Chart.yaml
> +description: A Helm chart to create the Kafka queues
```suggestion
description: A Helm chart to create the Kafka queues required by Palisade
```

2020-05-06 11:35 UTC, ac74475 commented on charts/kafka-queues/Chart.yaml
> +name: kafka-queues
can we make this name more descriptive and therefore also the name of the charts directory
```suggestion
name: create-palisade-kafka-queues
```

2020-05-06 11:35 UTC, ac74475 commented on charts/kafka/README.md
> +This chart was cloned from: https://github.com/helm/charts/tree/master/incubator/kafka
This statement is contradictory of the statement in the licence header

2020-05-06 11:35 UTC, ac74475 commented on charts/kafka/README.md
> +I have also added a testclient to test operation of the Kafka cluster.
```suggestion
I have also added a testclient pod to test operation of the Kafka cluster.
```

2020-05-06 11:35 UTC, ac74475 commented on charts/kafka/README.md
> +pod/palisade-kafka-testclient           1/1     Running   0          30m
Can we make it so this test client is only deployed when you specify some flag so we only deploy in dev/test environments and not in prod

2020-05-06 11:35 UTC, ac74475 commented on charts/kafka/README.md
> +$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
This instructions are for the original kafka charts. Might be worth moving down the earlier description around deployment and update this 'Installing the chart' section

2020-05-06 11:35 UTC, ac74475 commented on Jenkinsfile
> +    imagePullPolicy: Never
Never???

2020-05-06 11:35 UTC, ac74475 commented on Jenkinsfile
> +    imagePullPolicy: Never
Never???

2020-05-06 11:35 UTC, ac74475 commented on kafka-queues/create-topics.sh
> +    if [ -n "$TOPIC0" ]; then
Is it possible to make this a loop through a collection of Topics rather than 10 if statements?

2020-05-06 11:35 UTC, ac74475 commented on kafka-queues/pom.xml
> +    <artifactId>kafka-queues</artifactId>
update the name to be a bit more descriptive
```suggestion
    <artifactId>create-kafka-queues</artifactId>
```

2020-05-06 11:35 UTC, ac74475 commented on kafka-queues/pom.xml
> +                    <!--</buildArgs>-->
If this section is not required, can we remove it please

2020-05-06 11:35 UTC, ac74475 commented on kafka-queues/src/main/resources/values.yaml
> +  repository: palisade/@artifactId@
other charts don't use the repository label and instead just define the image name
```suggestion
  name:@artifactId@
```

2020-05-07 08:24 UTC, ac74475 requested changes
Mostly just needs the readme updating for Kafka given the changes made to the charts.
Am also assuming that there isn't any other readme's that need updating

2020-05-07 08:24 UTC, ac74475 commented on charts/create-kafka-queues/values.yaml
> +  name: kafka-queues
```suggestion
  name: create-kafka-queues
```

2020-05-07 08:24 UTC, ac74475 commented on charts/kafka/README.md
> -Copyright 2020 Crown Copyright
My previous comment about contradictory was the way we have two mentions of where we got this file from which point to two different addresses. We will need this licence header putting back in

2020-05-07 08:24 UTC, ac74475 commented on charts/kafka/README.md
>  # Apache Kafka Helm Chart
I think we should update this readme, sticking to the original format, such that it is an accurate reflection of how to use these charts.

2020-05-07 08:24 UTC, ac74475 commented on charts/kafka/README.md
>  # Apache Kafka Helm Chart
Might be worth renaming to 
```suggestion
# Palisade Apache Kafka Helm Chart
```

2020-05-07 08:24 UTC, ac74475 commented on create-kafka-queues/pom.xml
> +                    <!--</buildArgs>-->
remove commented out section
```suggestion
```

2020-05-07 09:37 UTC, dev-958 submitted a review, later dismissed

2020-05-07 10:42 UTC, ac74475 requested changes
a few small tweaks

2020-05-07 10:42 UTC, ac74475 commented on charts/kafka/README.md
> +|kafka.install|***Default=true***, determine whether the kafka and zookeeper charts should be installed|
```suggestion
|kafka.install|Determine whether the kafka and zookeeper charts should be installed, **Default=true**|
```

2020-05-07 10:42 UTC, ac74475 commented on charts/kafka/README.md
> +|testClientEnabled | Informs helm to install the kafka test client, which can be used to interrogate the cluster **default=true**|
```suggestion
|testClientEnabled | Informs helm to install the kafka test client, which can be used to interrogate the cluster. Recommend disabling for production deployment, **default=true**|
```

2020-05-07 10:42 UTC, ac74475 commented on charts/kafka/README.md
> +|global.localMountKafka.enabled| Informs helm that a remote AWS mounted EFS volume should be used for the kafka queue storage area, In this case: global.localMount.volumeHandle will be used for the v
What is the default for this parameter?

2020-05-07 10:42 UTC, ac74475 commented on charts/kafka/README.md
> +|`testClientEnabled` | Informs helm to install the kafka test client, which can be used to interrogate the cluster **default=true**|
Given we have defined these above, I don't think we need them here

2020-05-07 10:42 UTC, ac74475 commented on charts/kafka/README.md
> +##Overview of changes
```suggestion
## Overview of changes
```

2020-05-07 10:42 UTC, ac74475 commented on charts/kafka/README.md
> +1) A testclient pod to test operation of the Kafka cluster has been added controlled by operation of the parameter: testClientEnabled (see below)
```suggestion
1) A testclient pod to test operation of the Kafka cluster has been added, controlled by operation of the parameter: testClientEnabled (see below)
```

2020-05-07 11:48 UTC, ac74475 approved these changes

2020-05-07 11:50 UTC, merged