Pal 192 audit service unit tests
gchq/Palisade-services pull request #15
Opened 2019-10-18 11:49 UTC by dev930018

2019-10-18 13:28 UTC, dev-958 requested changes
Please remove all EqualsBuilder() and HashCodeBuilder() calls and use the intellij code generation tools.

2019-10-18 13:28 UTC, dev-958 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/request/ReadRequestCompleteAuditRequest.java
> +        return new EqualsBuilder()
Remove dependencies on EqualsBuilder() and use the intellij tool to generate the code

2019-10-18 13:28 UTC, dev-958 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/request/ReadRequestCompleteAuditRequest.java
> +        return new HashCodeBuilder(29, 37)
Remove dependencies on HashCodeBuilder() and use the intellij tool to generate the code

2019-10-22 11:23 UTC, dev-958 requested changes
one comment...

2019-10-22 11:23 UTC, dev-958 commented on audit-service/pom.xml
> +        <dependency>
why are you including the palisade as a test dependency?

2019-10-22 12:13 UTC, dev-958 submitted a review, later dismissed

2019-10-24 08:10 UTC, dev-958 submitted a review, later dismissed
the palisade-service is still referenced in the pom

2019-10-24 10:53 UTC, dev930018 commented
Please ignore the above, should have been for the resource unit tests

2019-10-28 08:06 UTC, nw1984 approved these changes

2019-10-28 10:35 UTC, m09526 approved these changes

2019-10-28 11:27 UTC, merged