PAL-564 k8s performance tests
gchq/Palisade-services pull request #160
Opened 2020-08-03 11:31 UTC by dev930018

2020-08-03 11:46 UTC, pd104923 submitted a review, later dismissed

2020-08-04 10:35 UTC, developer01189998819991197253 submitted a review, later dismissed

2020-08-05 10:02 UTC, ac74475 requested changes
Looks good, one small tweak

2020-08-05 10:02 UTC, ac74475 commented on palisade-service/src/main/java/uk/gov/gchq/palisade/service/palisade/service/ResourceService.java
> +            LOGGER.info("Got {} resources, first three are:  {}", response.size(), response.stream().limit(3).collect(Collectors.toSet()));
can this be updated to only show the resource id rather than the entire leaf resource object

2020-08-06 13:32 UTC, ac74475 approved these changes

2020-08-06 13:49 UTC, merged