Pal 145 move data services into services repo
gchq/Palisade-services pull request #19
Opened 2019-10-24 09:55 UTC by nw1984

2019-10-24 13:08 UTC, m09526 requested changes
Nice changes. Minor mods needed.

2019-10-24 13:08 UTC, m09526 commented on data-service/pom.xml
> +            <version>1.4.7.RELEASE</version>
Remove version number

2019-10-24 13:08 UTC, m09526 commented on data-service/pom.xml
> +        <dependency>
Is this dependency needed?

2019-10-24 13:08 UTC, m09526 commented on data-service/pom.xml
> +            <version>0.4.1-SNAPSHOT</version>
Change version to use ${project.parent.version}

2019-10-24 13:08 UTC, m09526 commented on data-service/pom.xml
> +            <version>${parent.version}</version>
Change version to use ${project.parent.version}

2019-10-24 13:08 UTC, m09526 commented on data-service/pom.xml
> +            <version>0.4.1-SNAPSHOT</version>
Change version to use ${project.parent.version}

2019-10-24 13:08 UTC, m09526 commented on data-service/src/main/java/uk/gov/gchq/palisade/service/data/web/DataServiceController.java
> +    @PostMapping(value = "/read/chunked", consumes = "application/json", produces = MediaType.APPLICATION_JSON_VALUE)
Is this produces parameter right? This sends back an octet stream.

2019-10-25 09:37 UTC, dev-958 requested changes
See comments

2019-10-25 09:37 UTC, dev-958 commented on data-service/src/main/java/uk/gov/gchq/palisade/service/data/config/ApplicationConfiguration.java
> +        AuditService audService = auditService(auditClient);
No! You already have a bean of type AuditService, inject that.

2019-10-25 09:37 UTC, dev-958 commented on data-service/src/main/java/uk/gov/gchq/palisade/service/data/config/ApplicationConfiguration.java
> +                                               final AuditClient auditClient,
inject PalisadeService

2019-10-25 09:37 UTC, dev-958 commented on data-service/src/main/java/uk/gov/gchq/palisade/service/data/config/ApplicationConfiguration.java
> +                                               final AuditClient auditClient,
inject AuditRequestReceiver

2019-10-28 09:23 UTC, nw1984 commented on data-service/pom.xml
> +            <version>1.4.7.RELEASE</version>
spring-cloud-starter-parent is a starter parent that does not follow the normal spring cloud starter naming convention i.e it does not follow that standard bill of materials format.
I have added in a specific property for this.

2019-10-29 13:36 UTC, m09526 submitted a review, later dismissed

2019-10-31 14:53 UTC, dev-958 submitted a review, later dismissed

2019-11-01 22:29 UTC, m09526 requested changes

2019-11-01 22:29 UTC, m09526 commented on audit-service/maven_output.txt
> +Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T20:00:29+01:00)
This file is immense and also contains personal data like names in the file path. This shouldn't be here.

2019-11-04 10:12 UTC, merged