Pal 919 topic offset actor system
gchq/Palisade-services pull request #209
Opened 2020-11-18 14:14 UTC by dev930018

* removed spring web in preparation for later ticket
* added topic offset actor system

2020-11-24 08:37 UTC, pd104923 approved these changes, later dismissed

2020-11-24 09:28 UTC, dbz120896 approved these changes, later dismissed

2020-11-25 23:06 UTC, dev-958 requested changes
Seems to be no expectation that persistence throws exceptions. Extra message type and state required now, add the reporting at a later stage when we put it in for Kafka handling.

2020-11-25 23:06 UTC, dev-958 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/config/ApplicationConfiguration.java
> +     * Create the TokenOffsetActorSsytem, controlling get access to the persistence layer and asynchronously blocking until offsets
If you are blocking, you are not doing reactive, you are not doing akka. Are you sure this statement is correct?

2020-11-25 23:06 UTC, dev-958 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/repository/TokenOffsetActorSystem.java
> +public final class TokenOffsetActorSystem extends AbstractBehavior<TokenOffsetActorSystem.TokenOffsetCmd> {
This is a really terrible name. Having "ActorSystem" in it makes it seem like a subclass of the akka ActorSystem - which it is not. In programming terms it's a controller.

2020-11-25 23:06 UTC, dev-958 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/repository/TokenOffsetActorSystem.java
> +    private final HashMap<String, ActorRef<WorkerCmd>> inFlightWorkers = new HashMap<>();
just "workers" would be fine, yes?

2020-11-25 23:06 UTC, dev-958 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/repository/TokenOffsetActorSystem.java
> +                // Easier to do ActorFlow().to(Sink.ignore) than ActorSink()
let this be our secret, eh?

2020-11-25 23:06 UTC, dev-958 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/repository/TokenOffsetActorSystem.java
> +                // Downcast SetOffset to Pair<String, Long>
not strictly a downcast

2020-11-26 11:08 UTC, dev930018 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/repository/TokenOffsetActorSystem.java
> +public final class TokenOffsetActorSystem extends AbstractBehavior<TokenOffsetActorSystem.TokenOffsetCmd> {
The object produced by the `create` method, which is the only "constructor" in the class, is an ActorSystem, even though the class is an implementation of Behaviors
Happy to rename if you think Controller is better

2020-11-26 11:17 UTC, dev930018 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/repository/TokenOffsetActorSystem.java
> +                // Easier to do ActorFlow().to(Sink.ignore) than ActorSink()
This used to be a downcast from `class AckTellWorker implements Pair<A, B>` to `class Pair<A, B>`, and the code was just `.map(x -> x)`. Removed as irrelevant

2020-11-26 11:18 UTC, dev930018 commented on filtered-resource-service/src/main/java/uk/gov/gchq/palisade/service/filteredresource/repository/TokenOffsetActorSystem.java
> +                // Downcast SetOffset to Pair<String, Long>
This used to be a downcast from `class AckTellWorker implements Pair<A, B>` to `class Pair<A, B>`, and the code was just `.map(x -> x)`
Removed as irrelevant

2020-11-30 11:51 UTC, dev-958 approved these changes
Excellent

2020-11-30 12:05 UTC, merged