Pal 958 palisade service kafka errors
gchq/Palisade-services pull request #230
Opened 2021-01-12 11:48 UTC by dev930018

2021-01-12 12:10 UTC, dev930018 commented
Tweaks such that both palisade-service and filtered-resource-service report themselves healthy in k8s

2021-01-12 15:21 UTC, pd104923 requested changes
One minor question.

2021-01-12 15:21 UTC, pd104923 commented on charts/palisade-service/templates/deployment.yaml
> +          value: {{ include "filtered-resource-service.config.path" . }}
`filtered-resource-service`, are you sure about that?
```suggestion
          value: {{ include "palisade-service.deployment.path" . }}
        - name: "SPRING_CONFIG_ADDITIONAL_LOCATION"
          value: {{ include "palisade-service.config.path" . }}
```

2021-01-12 16:55 UTC, pd104923 approved these changes
All good 😄

2021-01-13 16:41 UTC, developer01189998819991197253 approved these changes

2021-01-13 17:57 UTC, dev-958 approved these changes

2021-01-13 18:29 UTC, merged