Pal 490 k8s performance test
gchq/Palisade-services pull request #236
Opened 2021-01-25 16:36 UTC by dev930018

2021-02-01 09:24 UTC, dev-958 approved these changes, later dismissed

2021-02-02 09:32 UTC, kg981167224 submitted a review, later dismissed

2021-02-02 09:35 UTC, dev-958 submitted a review, later dismissed

2021-02-02 11:01 UTC, pd104923 requested changes
Just noticed a couple of copyrights that need to be reverted back

2021-02-02 11:01 UTC, pd104923 commented on resource-service/src/main/resources/schema.sql
> + * Copyright 2021 Crown Copyright
```suggestion
 * Copyright 2018-2021 Crown Copyright
```

2021-02-02 11:01 UTC, pd104923 commented on resource-service/src/main/resources/values.yaml
> +# Copyright 2019 Crown Copyright
```suggestion
# Copyright 2018-2021 Crown Copyright
```

2021-02-02 11:09 UTC, pd104923 submitted a review, later dismissed

2021-02-02 16:40 UTC, dev-958 approved these changes

2021-02-02 16:40 UTC, merged