PAL-569, updated copyrights within the Palisade Service
gchq/Palisade-services pull request #237
Opened 2021-01-26 14:18 UTC by developer01189998819991197253

2021-01-26 16:10 UTC, kg981167224 requested changes
Think it needs some changes.

2021-01-26 16:10 UTC, kg981167224 commented on audit-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/audit/ContractTestData.java
> +    public static final String ERROR_REQUEST_JSON = "{\"userId\":\"test-user-id\",\"resourceId\":\"/test/resourceId\",\"context\":{\"class\":\"uk.gov.gchq.palisade.Context\",\"contents\":{\"purpose\"
This section doesn't look correct.

2021-01-26 16:10 UTC, kg981167224 commented on audit-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/audit/ContractTestData.java
> +    public static final String BAD_SUCCESS_REQUEST_JSON = "{\"userId\":\"test-user-id\",\"resourceId\":\"/test/resourceId\",\"context\":{\"class\":\"uk.gov.gchq.palisade.Context\",\"contents\":{\"pur
JSON timestamp looks wrong

2021-01-26 16:10 UTC, kg981167224 commented on audit-service/README.md
> +   "timestamp":"2018-2021-11-26T10:28:54.118082Z",
Timestamp isn't valid

2021-01-26 16:10 UTC, kg981167224 commented on audit-service/README.md
> +   "timestamp":"2018-2021-11-26T10:32:28.818842Z",
Timestamp isn't valid

2021-01-26 16:28 UTC, developer01189998819991197253 commented on audit-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/audit/ContractTestData.java
> +    public static final String ERROR_REQUEST_JSON = "{\"userId\":\"test-user-id\",\"resourceId\":\"/test/resourceId\",\"context\":{\"class\":\"uk.gov.gchq.palisade.Context\",\"contents\":{\"purpose\"
reset, good spot

2021-01-26 16:29 UTC, developer01189998819991197253 commented on audit-service/README.md
> +   "timestamp":"2018-2021-11-26T10:28:54.118082Z",
reset

2021-01-26 16:29 UTC, developer01189998819991197253 commented on audit-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/audit/ContractTestData.java
> +    public static final String BAD_SUCCESS_REQUEST_JSON = "{\"userId\":\"test-user-id\",\"resourceId\":\"/test/resourceId\",\"context\":{\"class\":\"uk.gov.gchq.palisade.Context\",\"contents\":{\"pur
reset

2021-01-26 16:29 UTC, developer01189998819991197253 commented on audit-service/README.md
> +   "timestamp":"2018-2021-11-26T10:32:28.818842Z",
reset

2021-01-27 11:47 UTC, kg981167224 approved these changes
Can't see anything missed.

2021-01-27 18:49 UTC, dev930018 approved these changes

2021-01-27 18:49 UTC, merged