Pal 226 completable future feign bug
gchq/Palisade-services pull request #24
Opened 2019-10-29 16:25 UTC by dev930018

2019-10-29 16:57 UTC, Leg60 reviewed
Integration test now passes. Happy that a user is now returned.

2019-10-30 09:05 UTC, nw1984 requested changes

2019-10-30 09:05 UTC, nw1984 commented on palisade-service/src/main/java/uk/gov/gchq/palisade/service/palisade/service/PolicyService.java
> +            policy = CompletableFuture.supplyAsync(() -> this.client.getPolicy(policyRequest));
```suggestion
            policy = CompletableFuture.supplyAsync(() -> client.getPolicy(policyRequest));
```

2019-10-30 09:05 UTC, nw1984 commented on palisade-service/src/main/java/uk/gov/gchq/palisade/service/palisade/service/ResourceService.java
> +            resources = CompletableFuture.supplyAsync(() -> this.client.getResourcesById(resource));
```suggestion
            resources = CompletableFuture.supplyAsync(() -> client.getResourcesById(resource));
```

2019-10-30 09:05 UTC, nw1984 commented on palisade-service/src/main/java/uk/gov/gchq/palisade/service/palisade/service/UserService.java
> +            user = CompletableFuture.supplyAsync(() -> this.userClient.getUser(request));
```suggestion
            user = CompletableFuture.supplyAsync(() -> userClient.getUser(request));
```

2019-10-30 09:05 UTC, nw1984 commented on palisade-service/src/main/java/uk/gov/gchq/palisade/service/palisade/web/ResourceClient.java
I question the merits of returning a synchronous function for all of the ResourceService - some of these resources could take a long time to complete.

Spring guide here on implementing async methods:
https://spring.io/guides/gs/async-method/

Any test harness that uses the async method will have to do an asyncDispatch() to ensure that the async call is completed.

2019-10-30 09:05 UTC, nw1984 commented on palisade-service/src/main/java/uk/gov/gchq/palisade/service/palisade/web/UserClient.java
> +    User getUser(final GetUserRequest request);
ditto above.

2019-11-01 21:58 UTC, m09526 approved these changes

2019-11-02 20:08 UTC, dev-958 approved these changes

2019-11-04 09:15 UTC, merged