PAL-988 removed post-install from already-waiting create-topics job
gchq/Palisade-services pull request #250
Opened 2021-02-10 15:07 UTC by dev930018

Removed the post-install hook in favor of the default on-install mechanism. This should fix the pipeline deadlock problem.

This further offers the opportunity to use the `--wait` flag when setting up for the k8s smoke test to ensure all pods are ready before running

2021-02-10 16:26 UTC, developer01189998819991197253 submitted a review, later dismissed

2021-02-10 18:49 UTC, dev-958 requested changes

2021-02-10 18:49 UTC, dev-958 commented on charts/create-kafka-queues/templates/job.yaml
>    annotations:
you don't need this annotation section at all then.

2021-02-11 12:05 UTC, kg981167224 approved these changes

2021-02-11 12:14 UTC, developer01189998819991197253 approved these changes

2021-02-12 14:57 UTC, dev-958 approved these changes

2021-02-12 14:57 UTC, merged