PAL-971 made error topic consumer static across test class
gchq/Palisade-services pull request #253
Opened 2021-02-15 17:38 UTC by dev930018

2021-02-18 11:24 UTC, pd104923 requested changes
Small spelling mistake to correct.

2021-02-18 11:24 UTC, pd104923 commented on filtered-resource-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/filteredresource/kafka/KafkaRestWebSocketContractTest.java
> +                    // Expect tot receive the three resources and no errors
```suggestion
                    // Expect to receive the three resources and no errors
```

2021-02-18 16:49 UTC, pd104923 approved these changes

2021-02-18 16:53 UTC, developer01189998819991197253 approved these changes

2021-02-22 08:39 UTC, dev-958 approved these changes

2021-02-22 08:47 UTC, merged