PAL-1005 added wait-for-services script
gchq/Palisade-services pull request #258
Opened 2021-02-24 17:39 UTC by dev930018

2021-03-01 07:22 UTC, kg981167224 submitted a review, later dismissed
Just check if you agree with comments.

2021-03-01 07:22 UTC, kg981167224 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@PAL-1005-create-kafka-queues-delete-job')_
Remove before Merge.

2021-03-01 07:22 UTC, kg981167224 commented on create-kafka-queues/wait-for-services.sh
> +  until nc -vz $dest $port > /dev/null 2>&1; do
Would we want a timeout and appropriate error message for this. Since if it hangs it will tie up resources until it is manually killed.

2021-03-04 15:32 UTC, dev-958 requested changes
See comments. I think values from other charts need to be used so that changing ports or names don't break this.

2021-03-04 15:32 UTC, dev-958 commented on charts/create-kafka-queues/values.yaml
> +  zookeeper: palisade-zookeeper:2181
Seems a bit dodgy hard-coding the port in here, or even the zookeeper name. Can we not compose these in a _helpers template function using the values provided in the origin charts?

2021-03-04 15:32 UTC, dev-958 commented on charts/create-kafka-queues/values.yaml
> +waitForServices:
Again, I would compose these somehow. Too easy to break it.

2021-03-04 15:32 UTC, dev-958 commented on create-kafka-queues/src/main/resources/values.yaml
> +  zookeeper: palisade-zookeeper:2181
same.

2021-03-04 15:32 UTC, dev-958 commented on create-kafka-queues/src/main/resources/values.yaml
> +waitForServices:
again

2021-03-05 17:59 UTC, dev-958 approved these changes

2021-03-08 08:40 UTC, merged