Pal 504 unused services dependencies
gchq/Palisade-services pull request #265
Opened 2021-03-04 15:34 UTC by dev930018

2021-03-05 12:52 UTC, pd104923 approved these changes, later dismissed

2021-03-09 09:55 UTC, developer01189998819991197253 requested changes

2021-03-09 09:55 UTC, developer01189998819991197253 commented on palisade-service/pom.xml
> +        <dependency>
add the missing <!--- Palisade ---> tag

2021-03-09 09:55 UTC, developer01189998819991197253 commented on user-service/pom.xml
> +            <!-- Caffeine local caching -->
use the same tag as used in the Policy service
```suggestion
            <!-- Caffeine local cache provider -->
```

2021-03-11 10:35 UTC, developer01189998819991197253 approved these changes

2021-03-12 17:13 UTC, dev-958 approved these changes

2021-03-12 17:14 UTC, merged