PAL-1012, blank space readme change to force PR
gchq/Palisade-services pull request #275
Opened 2021-03-16 11:01 UTC by developer01189998819991197253

2021-03-18 17:53 UTC, developer01189998819991197253 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@feature/PAL-1012-ExamplesLoggingDependency')_
Will revert back after code has passed review stage

2021-03-19 07:45 UTC, kg981167224 approved these changes, later dismissed

2021-03-19 15:34 UTC, dev-958 submitted a review, later dismissed

2021-03-22 11:22 UTC, dev930018 commented on templates/classpath-jars-pv.yaml
> +    "helm.sh/hook": "pre-install, pre-upgrade"
What was the conclusion on this? If we have it pre-upgrade do we also need a hook-delete-policy?

2021-03-24 19:52 UTC, dev930018 commented on charts/create-kafka-queues/templates/job.yaml
> +        command: ["/bin/bash", "/bin/wait-for-services.sh" ]
Sorry to nitpick
```suggestion
        command: ["/bin/bash", "/bin/wait-for-services.sh"]
```

2021-03-26 13:58 UTC, developer01189998819991197253 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@feature/PAL-1012-ExamplesLoggingDependency')_
```suggestion
@Library('jenkinsfile-lib')_
```

2021-03-31 11:41 UTC, dev930018 requested changes

2021-03-31 11:41 UTC, dev930018 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@PAL-1012-clean-non-namespaced-resources')_
```suggestion
@Library('jenkinsfile-lib')_
```

2021-03-31 13:53 UTC, dev930018 approved these changes

2021-03-31 13:57 UTC, merged