Pal 234 move integration tests
gchq/Palisade-services pull request #29
Opened 2019-11-07 11:25 UTC by dev930018

`mvn clean test` reports a build time of ~1-2mins

2019-11-08 14:51 UTC, dev-958 submitted a review, later dismissed

2019-11-08 15:13 UTC, m09526 requested changes

2019-11-08 15:13 UTC, m09526 commented on data-service/src/main/java/uk/gov/gchq/palisade/service/data/request/AddCacheRequest.java
> +import org.codehaus.jackson.annotate.JsonIgnoreProperties;
There is a dependency conflict here somewhere! Some classes are using different versions of Jackson. Check the package names! com.fasterxml is the up to date Jackson! Please check the dependency list that this module is pulling in.

2019-11-11 08:03 UTC, nw1984 submitted a review, later dismissed

2019-11-11 09:47 UTC, m09526 commented on data-service/src/main/java/uk/gov/gchq/palisade/service/data/request/GetCacheRequest.java
> +import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
This is the correct import.

2019-11-11 11:08 UTC, m09526 approved these changes

2019-11-11 11:08 UTC, merged