Pal 235 add integration tests to jenkins
gchq/Palisade-services pull request #30
Opened 2019-11-07 16:43 UTC by dev930018

Tested on integration-tests/PAL-163... will have tests pass and jenkins report success. Blocked until integration-tests repo can be `mvn install`ed

2019-11-11 08:00 UTC, nw1984 requested changes
The jenkins build fails with the following errors:

[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/jenkins/agent/workspace/add-integration-tests-to-jenkins). Please verify you invoked Maven from the correct directory. -> [Help 1]

2019-11-11 08:02 UTC, nw1984 requested changes

2019-11-11 08:02 UTC, nw1984 commented on Jenkinsfile
> +            git branch: "develop", url: 'https://github.com/gchq/Palisade-integration-tests.git'
This is a Jenkins build for this repository only. The integration-test branch itself will need a Jenkins build in it's own right.

2019-11-11 14:34 UTC, dev930018 commented
Commit [855b5b1](https://github.com/gchq/Palisade-services/pull/30/commits/855b5b132c7e216f3897ea8f71225736614f8f9e) validated working on jenkins using a working integration-tests branch. Jenkins build here will pass once integration-tests/develop has tests merged

2019-11-12 09:28 UTC, nw1984 approved these changes

2019-11-12 14:12 UTC, m09526 approved these changes

2019-11-12 16:33 UTC, merged