Pal 58 traefik tls
gchq/Palisade-services pull request #319
Opened 2021-05-27 14:16 UTC by developer01189998819991197253

2021-06-02 07:37 UTC, pd104923 approved these changes, later dismissed

2021-06-02 16:23 UTC, dev930018 requested changes

2021-06-02 16:23 UTC, dev930018 commented on charts/traefik/templates/config-map.yaml
> +stringData:
```suggestion
# ATTENTION
# While TLS certs are included as secrets here, take note:
# * they are not used at this time by traefik
# * publishing certificate private-keys on an open-source repository is not appropriate for security
# If you require TLS certifictates for traefik, this is not the place for it
stringData:
```

2021-06-02 16:25 UTC, dev930018 approved these changes, later dismissed

2021-06-03 12:06 UTC, developer01189998819991197253 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@feature/PAL-58')_
```suggestion
@Library('jenkinsfile-lib')_
```

2021-06-03 12:10 UTC, merged