Pal 1034 add gitattributes
gchq/Palisade-services pull request #322
Opened 2021-06-01 14:01 UTC by pd104923

- Added gitattributes file
- Updated gitignore to include jvm example log and err files
- All files have been normalised based on the new git configs so line endings have changed for some of them.
- All Dockerfiles have had any `sed` operations removed

2021-06-01 15:25 UTC, m78233 approved these changes, later dismissed

2021-06-02 11:52 UTC, developer01189998819991197253 requested changes
A lot of files have no changes, just line endings. Can you remove the files that have not been edited please

2021-06-02 12:50 UTC, pd104923 commented
> A lot of files have no changes, just line endings. Can you remove the files that have not been edited please

This is due to the changes that were made for this ticket. When doing a `git add --renormalize .` for the repo these files had their line endings updated.

2021-06-02 13:03 UTC, developer01189998819991197253 commented on .gitignore
> +*.err
are these changes needed?

2021-06-02 15:46 UTC, developer01189998819991197253 requested changes

2021-06-02 15:46 UTC, developer01189998819991197253 commented on .gitattributes
> +# Set the default behavior, in case people don't have core.autocrlf set
add Palisade license header

2021-06-03 09:15 UTC, developer01189998819991197253 approved these changes

2021-06-03 09:40 UTC, merged