Pal 1030 deploy to ref
gchq/Palisade-services pull request #325
Opened 2021-06-04 10:36 UTC by pd104923

2021-06-09 10:59 UTC, pd104923 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@feature/PAL-1030-deploy-to-ref')_
This needs to be reverted.

2021-06-09 11:10 UTC, pd104923 commented on licenses/mit_license.html
> +<link type="text/css" rel="stylesheet" href="https://opensource.org/sites/all/themes/bootstrap-business/css/ie8.css?qsj6ct" media="all" />
This license will be reverted

2021-06-09 14:31 UTC, m78233 submitted a review, later dismissed
I think that is right

2021-06-09 15:12 UTC, developer01189998819991197253 requested changes

2021-06-09 15:12 UTC, developer01189998819991197253 commented on Jenkinsfile
> +@Library('jenkinsfile-lib@feature/PAL-1030-deploy-to-ref')_
```suggestion
@Library('jenkinsfile-lib')_
```

2021-06-09 15:12 UTC, developer01189998819991197253 commented on templates/kafka-proxy-svc.yaml
> +  {{- if .Values.global.kafka.install }}
wouldnt it makes sense to do an `if you deployed kafka and redis, and the hosting is aws`? 
Doesnt this affect the local deploy?

2021-06-11 11:37 UTC, developer01189998819991197253 approved these changes

2021-06-14 09:41 UTC, dev930018 approved these changes

2021-06-14 09:41 UTC, merged