PAL-636 added rest controller test, added assertions where missing in…
gchq/Palisade-services pull request #336
Opened 2021-06-30 14:16 UTC by developer01189998819991197253

… Audit Service

2021-06-30 16:02 UTC, pd104923 requested changes
1 minor suggestion

2021-06-30 16:02 UTC, pd104923 commented on audit-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/audit/kafka/KafkaContractRestTest.java
> +                .forEach(File::deleteOnExit);
If we're only using the peek to write out a logger message could these be collated into the forEach method?
```suggestion
                .filter(file -> (file.getName().startsWith("Success") || file.getName().startsWith("Error")))
                .forEach((File file) -> {
                    LOGGER.info("Deleting file {}", file.getName());
                    file.deleteOnExit;
                });
```

2021-07-05 08:23 UTC, pd104923 submitted a review, later dismissed

2021-07-06 14:57 UTC, dev930018 approved these changes

2021-07-07 12:04 UTC, merged