Pal 1082 remove resource parent
gchq/Palisade-services pull request #339
Opened 2021-07-02 14:53 UTC by dev930018

Awaiting on [PAL-1023](https://github.com/gchq/Palisade-services/pull/332) being merged

2021-07-08 08:26 UTC, pd104923 requested changes
Some small changes

2021-07-08 08:26 UTC, pd104923 commented on policy-service/src/main/java/uk/gov/gchq/palisade/service/policy/config/PolicyConfiguration.java
> +    // Allow generics wildcard
```suggestion
    // Allow generics wildcard
    @SuppressWarnings("java:S1452")
```
Should the comment come before the suppression?

2021-07-08 08:26 UTC, pd104923 commented on topic-offset-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/topicoffset/kafka/KafkaContractTest.java
> +        //Suppress ternary operator smell
```suggestion
// Suppress ternary operator smell
@SuppressWarnings("java:S1774")
```

2021-07-08 08:26 UTC, pd104923 commented on topic-offset-service/src/contract-tests/java/uk/gov/gchq/palisade/contract/topicoffset/kafka/KafkaTestConfiguration.java
> +        // Suppress specific exception smell
```suggestion
    // Suppress specific exception smell
    @SuppressWarnings("java:S112")
```
I think the comment should describe the smell that's being suppressed

2021-07-14 10:19 UTC, developer01189998819991197253 requested changes

2021-07-14 10:19 UTC, developer01189998819991197253 commented on NOTICES.md
> -* GCHQ Palisade Common Library ([uk.gov.gchq.palisade:common:0.5.0-RELEASE](https://github.com/gchq/Palisade-common))
revert

2021-07-14 10:19 UTC, developer01189998819991197253 commented on attribute-masking-service/mvn_dependency_tree.txt
> -uk.gov.gchq.palisade:attribute-masking-service:jar:0.5.0-RELEASE
revert, we're currently at a RELEASE

2021-07-14 10:19 UTC, developer01189998819991197253 commented on attribute-masking-service/src/main/java/uk/gov/gchq/palisade/service/attributemask/model/AttributeMaskingRequest.java
> +             * @param <T>   the domain class for the rules
```suggestion
             * @param <T> the domain class for the rules
```

2021-07-14 10:19 UTC, developer01189998819991197253 commented on audit-service/mvn_dependency_tree.txt
> +uk.gov.gchq.palisade:audit-service:jar:0.5.0-SNAPSHOT
revert changes to dependency trees

2021-07-14 10:19 UTC, developer01189998819991197253 commented on data-service/src/component-tests/java/uk/gov/gchq/palisade/component/data/service/DataSerialiserPrePopTest.java
> +@Disabled
delete disabled test

2021-07-14 10:19 UTC, developer01189998819991197253 commented on services-manager/README.md
> +The contents of this file are under substitution in the build process - maven's `process-resources` stage will substitute executable(dot)jar for this: services-manager-0.5.0-SNAPSHOT-exec.jar
revert changes

2021-07-14 13:54 UTC, dev930018 commented on attribute-masking-service/src/main/java/uk/gov/gchq/palisade/service/attributemask/model/AttributeMaskingRequest.java
> +             * @param <T>   the domain class for the rules
Indent to match javadoc line below

2021-07-14 15:49 UTC, developer01189998819991197253 approved these changes

2021-07-15 08:39 UTC, merged