Pal 1092 generate coderelease and tag
gchq/Palisade-services pull request #351
Opened 2021-07-19 16:32 UTC by dev930018

2021-07-22 15:31 UTC, m78233 commented on charts/attribute-masking-service/templates/_helpers.tpl
>  Calculate a storage name based on the code release artifact id or the supplied value of codeRelease
need to replace the text "codeRelease" with a suitable alternative.

2021-07-22 15:45 UTC, m78233 commented on charts/attribute-masking-service/templates/_helpers.tpl
>  Calculate a storage name based on the code release artifact id or the supplied value of codeRelease
Found two lingering references in the code to codeRelease: /templates/_helpers.tpl;  create-kafka-queues/src/main/resources/values.yaml

2021-07-22 15:49 UTC, m78233 requested changes
A couple of minor things to check-up on.

2021-07-23 12:32 UTC, m78233 approved these changes, later dismissed

2021-07-26 11:08 UTC, developer01189998819991197253 requested changes

2021-07-26 11:08 UTC, developer01189998819991197253 commented on NOTICES.md
> +* GCHQ Palisade Common Library ([uk.gov.gchq.palisade:common:0.5.0-SNAPSHOT](https://github.com/gchq/Palisade-common))
shouldnt this be 0.5.1?

2021-07-26 11:08 UTC, developer01189998819991197253 commented on audit-service/mvn_dependency_tree.txt
> +uk.gov.gchq.palisade:audit-service:jar:0.5.0-SNAPSHOT
needs to be rebuilt against 0.5.1 dependencies

2021-07-26 11:32 UTC, ac74475 requested changes
doesnt work and negates the work that @m78233 did. Test it with the release profile and look at the tag on the docker images created

2021-07-26 14:02 UTC, ac74475 submitted a review, later dismissed
it now works for the release profiles

2021-07-26 14:11 UTC, dev930018 commented
Changes to resource-service to fix sonarqube smell [here](https://palisade-prod.apps.gss.gov.uk/sonarqube/project/issues?id=Palisade-Services-PAL-1092-generate-coderelease-and-tag&issues=AXrixArNRy8TgjbXaE3v&open=AXrixArNRy8TgjbXaE3v)

2021-07-26 14:26 UTC, developer01189998819991197253 requested changes
Approved pending license revert

2021-07-26 14:26 UTC, developer01189998819991197253 commented on licenses/mit_license.html
> -<link type="text/css" rel="stylesheet" href="https://opensource.org/sites/all/themes/bootstrap-business/css/ie8.css?qqdhfs" media="all" />
revert license change

2021-07-28 14:12 UTC, ac74475 requested changes, later dismissed

2021-07-28 14:12 UTC, ac74475 commented on services-manager/pom.xml
>                                      <!--suppress UnresolvedMavenProperty -->
the readers.app.revision starts with a dash that needs removing to fix the JVM deployment

2021-07-29 08:45 UTC, merged