PAL-275 move hadoop resource service
gchq/Palisade-services pull request #42
Opened 2019-11-25 14:09 UTC by nw1984

2019-11-25 17:16 UTC, m09526 requested changes

2019-11-25 17:16 UTC, m09526 commented on resource-service/pom.xml
>              <version>0.3.0</version>
Extract version

2019-11-25 17:16 UTC, m09526 commented on services-launcher/.log
> +Error: Invalid or corrupt jarfile target
This file shouldn't be here.

2019-11-26 10:23 UTC, m09526 submitted a review, later dismissed

2019-11-26 16:33 UTC, dev-958 requested changes

2019-11-26 16:33 UTC, dev-958 commented on resource-service/pom.xml
> -        <dependency>
Removing this is likely to break ServiceInstanceRestController. Even though it doesn't call any Feign clients.

2019-11-28 12:30 UTC, merged