PAL-183 first pass
gchq/Palisade-services pull request #44
Opened 2019-11-28 08:53 UTC by nw1984

Test results as follows:

{code:bash}
$ helm delete palisade --purge
$ kubectl delete -f charts/traefik/templates/custom-resource.yaml
$ helm upgrade --install palisade . --set traefik.install=true
$ kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
audit-service-66dfbd7464-dh8h6      1/1     Running   0          42s
palisade-service-6dc5956656-sj7nv   1/1     Running   0          42s
user-service-757575d5cc-rbw7n       1/1     Running   0          41s
{code}

*Testing*
Log onto palisade-service and access user-service:

{code:bash}                                                                                                                                                                                           # kubectl exec -it palisade-service-6dc5956656-sj7nv sh
# curl -XPOST http://user-service/getUser -d "{}" -H "Content-Type: application/json"
{"timestamp":1574930539152,"status":500,"error":"Internal Server Error","message":"Type definition error: [simple type, class uk.gov.gchq.palisade.service.user.request.GetUserRequest]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `uk.gov.gchq.palisade.service.user.request.GetUserRequest`, problem: The originalRequestId cannot be set to null.\n at [Source: (PushbackInputStream); line: 1, column: 2]","path":"/getUser"}# 
# curl -XPOST http://user-service/addUser -d "{}" -H "Content-Type: application/json"
{"timestamp":1574930603929,"status":500,"error":"Internal Server Error","message":"Type definition error: [simple type, class uk.gov.gchq.palisade.service.user.request.AddUserRequest]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `uk.gov.gchq.palisade.service.user.request.AddUserRequest`, problem: The originalRequestId cannot be set to null.\n at [Source: (PushbackInputStream); line: 1, column: 2]","path":"/addUser"}# 
{code}

2019-11-29 10:17 UTC, m09526 submitted a review, later dismissed

2019-12-02 11:10 UTC, dev-958 submitted a review, later dismissed

2019-12-02 15:16 UTC, m09526 submitted a review, later dismissed

2019-12-03 15:29 UTC, dev-958 requested changes
see inline

2019-12-03 15:29 UTC, dev-958 commented on charts/user-service/templates/deployment.yaml
> +        app.kubernetes.io/name: {{ include "palisade-service.name" . }}
here

2019-12-03 15:29 UTC, dev-958 commented on charts/user-service/templates/deployment.yaml
> +        app.kubernetes.io/instance: {{ .Release.Name }}
here

2019-12-06 10:29 UTC, m09526 approved these changes

2019-12-06 12:38 UTC, dev-958 approved these changes

2019-12-09 16:00 UTC, merged