PAL-184 helm chart for policy service
gchq/Palisade-services pull request #45
Opened 2019-11-29 11:46 UTC by nw1984

2019-12-02 11:12 UTC, m09526 requested changes
Several of the files have many mentions of the audit service, shouldn't these be policy-service? Please check the Helm names!

2019-12-02 11:44 UTC, dev-958 requested changes
See inline. Stop hurrying! No prizes for tickets.

2019-12-02 11:44 UTC, dev-958 commented on charts/policy-service/templates/deployment.yaml
> +    name: {{ include "audit-service.name" . }}
oops!

2019-12-02 11:44 UTC, dev-958 commented on charts/policy-service/templates/deployment.yaml
> +            {{ include "audit-service.labels" . | indent 4 }}
oops!

2019-12-02 11:44 UTC, dev-958 commented on charts/policy-service/templates/deployment.yaml
> +            app.kubernetes.io/name: {{ include "audit-service.name" . }}
oops!

2019-12-02 11:44 UTC, dev-958 commented on charts/policy-service/templates/deployment.yaml
> +                app.kubernetes.io/name: {{ include "audit-service.name" . }}
oops!

2019-12-02 11:44 UTC, dev-958 commented on charts/policy-service/templates/service.yaml
> +    name: {{ include "audit-service.name" . }}
oops!

2019-12-02 11:44 UTC, dev-958 commented on charts/policy-service/templates/service.yaml
> +        app.kubernetes.io/name: {{ include "audit-service.name" . }}
oops!

2019-12-02 15:17 UTC, m09526 submitted a review, later dismissed

2019-12-03 15:27 UTC, dev-958 requested changes
see inline

2019-12-03 15:27 UTC, dev-958 commented on charts/policy-service/templates/deployment.yaml
> +        app.kubernetes.io/name: {{ include "palisade-service.name" . }}
nope

2019-12-03 15:27 UTC, dev-958 commented on charts/policy-service/templates/deployment.yaml
> +        helm.sh/chart: {{ include "palisade-service.chart" . }}
nope

2019-12-06 12:04 UTC, dev-958 approved these changes

2019-12-06 16:39 UTC, m09526 approved these changes

2019-12-06 16:40 UTC, merged