Pal 261 logging improvements user service
gchq/Palisade-services pull request #48
Opened 2019-12-05 11:46 UTC by developer01189998819991197253

As this may be the first of many similar, it is worth ensuring the initial set of changes to the user service are complete

The ticket suggests:

Log at INFO level for receipt of a message
Log at INFO level for a message sent to another service
Log at DEBUG for individual function calls with more metadata
In the event of ERRORs include the METAdata of what was being handled
If this is the full set of cases for logging, we should only see messages on INFO if services are communicating with one another

2019-12-05 13:20 UTC, m09526 submitted a review, later dismissed

2019-12-05 14:24 UTC, dev-958 requested changes
comments inline

2019-12-05 14:24 UTC, dev-958 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/config/ApplicationConfiguration.java
> +            LOGGER.debug("Cache backing implementation = {}", Objects.requireNonNull(backingStores.values().stream().findFirst().orElse(null)).getClass().getSimpleName());
I really think this should be INFO, we would always want to no what cache type is in play. All been instantiation messages should be.

2019-12-05 14:24 UTC, dev-958 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/config/ApplicationConfiguration.java
> +        LOGGER.debug("Instantiated eurekaClient");
ditto

2019-12-05 14:24 UTC, dev-958 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/config/ApplicationConfiguration.java
> +            LOGGER.debug("Starting ThreadPoolTaskExecutor with core = [{}] max = [{}]", ex.getCorePoolSize(), ex.getMaxPoolSize());
ditto

2019-12-05 14:24 UTC, dev-958 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/exception/NoSuchUserIdException.java
> +        LOGGER.error("NoSuchUserIdException thrown with {} message", message);
I think it should be above the super() call as that could fail.

2019-12-05 14:24 UTC, dev-958 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/exception/NoSuchUserIdException.java
> +        LOGGER.error("NoSuchUserIdException thrown with {} message", message);
ditto

2019-12-05 14:24 UTC, dev-958 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/config/ApplicationConfiguration.java
> +        if (cacheService != null) {
All of this can be done with Optional. This is ugly.

2019-12-05 14:24 UTC, dev-958 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/repository/K8sBackingStore.java
>              if (configMap == null || configMap.getData().isEmpty()) {
wrap in Optional.

2019-12-05 15:26 UTC, m09526 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/exception/NoSuchUserIdException.java
> +        LOGGER.error("NoSuchUserIdException thrown with {} message", message);
Java says no

2019-12-05 16:10 UTC, developer01189998819991197253 commented on user-service/src/main/java/uk/gov/gchq/palisade/service/user/exception/NoSuchUserIdException.java
> +        LOGGER.error("NoSuchUserIdException thrown with {} message", message);
Super has to be the first line in the method

2019-12-06 10:14 UTC, m09526 submitted a review, later dismissed

2019-12-06 12:32 UTC, dev-958 submitted a review, later dismissed

2019-12-09 11:16 UTC, m09526 approved these changes

2019-12-09 11:21 UTC, dev-958 approved these changes

2019-12-10 14:47 UTC, merged