Pal 259 logging improvements for audit service
gchq/Palisade-services pull request #50
Opened 2019-12-06 14:58 UTC by developer01189998819991197253

As this may be the first of many similar, it is worth ensuring the initial set of changes to the user service are complete

The ticket suggests:

Log at INFO level for receipt of a message
Log at INFO level for a message sent to another service
Log at DEBUG for individual function calls with more metadata
In the event of ERRORs include the METAdata of what was being handled
If this is the full set of cases for logging, we should only see messages on INFO if services are communicating with one another

2019-12-06 15:48 UTC, dev-958 requested changes
It's overkill to log (even in debug) setters/getters in data objects. Yes log their contents once populated but it will render the logs unreadable.

2019-12-06 16:51 UTC, m09526 requested changes

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/request/AuditRequest.java
> +        LOGGER.debug("AuditRequest called");
Logging every constructor call is overkill

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/service/StroomAuditService.java
> +        LOGGER.debug("systemName is {}", SYSTEM.getName());
We don't need to log every getter and setter.

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/service/StroomAuditService.java
> +        LOGGER.debug("systemName is {}", systemName);
This method is simply calling the other one which is already logging.

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/service/StroomAuditService.java
> +        LOGGER.debug("systemEnv is {}", systemEnv);
As above

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/service/StroomAuditService.java
> +        LOGGER.debug("systemEnv is {}", SYSTEM.getEnvironment());
Don't log every getter

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/service/StroomAuditService.java
> +        LOGGER.debug("systemDescription is {}", description);
ditto

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/service/StroomAuditService.java
> +        LOGGER.debug("systemVersion is {}", systemVersion);
Ditto

2019-12-06 16:51 UTC, m09526 commented on audit-service/src/main/java/uk/gov/gchq/palisade/service/audit/service/StroomAuditService.java
> +        LOGGER.debug("systemClassification is {}", systemClassification);
As above

2019-12-09 11:16 UTC, m09526 approved these changes

2019-12-09 11:20 UTC, dev-958 approved these changes

2019-12-09 15:17 UTC, merged