Pal 289 data service helm charts
gchq/Palisade-services pull request #60
Opened 2019-12-17 13:00 UTC by dev930018

2019-12-17 16:55 UTC, dev930018 commented
Further required for this ticket:
Ingress on /data
Mount point for the associated data

2019-12-19 10:48 UTC, dev-958 requested changes
As it stands the data service does not come up because you have not defined a PersistentVolume to bind with the claim. This needs to be added and parameterised from the top level. Also allow for there to be multiple locations (an array). The volumes that are mounted should be written to output on install and update the README accordingly.

2020-01-07 17:44 UTC, dev-958 approved these changes

2020-01-09 16:48 UTC, dev-958 requested changes
PersistentVolume is not mounting

2020-01-14 10:26 UTC, nw1984 approved these changes

2020-01-23 08:44 UTC, closed without merging