PAL-149 first pass
gchq/Palisade-services pull request #9
Opened 2019-10-09 12:23 UTC by nw1984

Creation of policy service code

2019-10-10 14:42 UTC, dev-958 submitted a review, later dismissed

2019-10-10 14:52 UTC, m09526 requested changes

2019-10-10 14:52 UTC, m09526 commented on policy-service/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "name": "web.client.audit-service",
Please can the unused service properties be removed from this file? E.g. the policy service never speaks to the user service, so that property can be removed from here.

2019-10-10 14:52 UTC, m09526 commented on policy-service/src/main/java/uk.gov.gchq.palisade.service.policy/web/DefaultController.java
> +public class DefaultController {
Rename class to something more specific and descriptive.

2019-10-11 09:33 UTC, m09526 approved these changes

2019-10-11 09:34 UTC, merged